const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),script=html.match(/<script>([\s\S]*?)<\/script>/)[1];new vm.Script(script);
const ids=[...html.matchAll(/\sid="([^"]+)"/g)].map(x=>x[1]);assert.equal(new Set(ids).size,ids.length,'HTML IDs are unique');
const nodes={};const canvas=new Proxy({measureText:()=>({width:40})},{get:(o,k)=>k in o?o[k]:(...args)=>{if(['moveTo','lineTo','arc','fillRect','clearRect'].includes(k))assert(args.filter(x=>typeof x==='number').every(Number.isFinite),'finite canvas '+k);}});
for(const id of ids)nodes[id]={id,value:'',innerHTML:'',textContent:'',style:{},dataset:{},classList:{add(){},remove(){},toggle(){}},addEventListener(){},setAttribute(){},removeAttribute(){},hasAttribute(){return false;},querySelectorAll(){return[];},querySelector(){return null;},checkValidity(){return true;},reportValidity(){return true;},getBoundingClientRect(){return{width:600,height:315};},getContext(){return canvas;}};
for(const m of html.matchAll(/<input\b([^>]+)>/g)){const id=m[1].match(/\bid="([^"]+)"/)?.[1],v=m[1].match(/\bvalue="([^"]*)"/)?.[1];if(id)nodes[id].value=v||'';}
for(const m of html.matchAll(/<select\b[^>]*\bid="([^"]+)"[^>]*>([\s\S]*?)<\/select>/g)){const opts=[...m[2].matchAll(/<option\b([^>]*)>/g)],pick=opts.find(x=>/selected/.test(x[1]))||opts[0];nodes[m[1]].value=pick?.[1].match(/value="([^"]+)"/)?.[1]||'';}
let stored={};const ctx={console,Date,Math,Number,Map,Set,WeakMap,JSON,String,Array,Intl,AbortSignal,performance,URL,document:{getElementById:id=>{assert(nodes[id],'missing ID '+id);return nodes[id];},querySelectorAll:()=>[],documentElement:{dataset:{}}},window:{devicePixelRatio:1,addEventListener(){},innerWidth:1280,innerHeight:900},getComputedStyle:()=>({getPropertyValue:()=> '#aaa'}),localStorage:{getItem:k=>stored[k],setItem:(k,v)=>stored[k]=v},setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,fetch:async()=>{throw Error('offline test');}};
vm.createContext(ctx);const names=[...script.matchAll(/(?:async )?function (\w+)\(/g)].map(x=>x[1]);const tail=script.indexOf('let rt;window.addEventListener');assert(tail>0);vm.runInContext(script.slice(0,tail)+'Object.assign(globalThis,{state,'+names.join(',')+'});})();',ctx);
const DAY=86400000,HOUR=3600000;let count=0;function test(name,fn){fn();count++;console.log('PASS',name);}function near(a,b,t=1e-8){assert(Math.abs(a-b)<t,`${a} ≈ ${b}`);}
function seed(){ctx.state.daily=Array.from({length:900},(_,i)=>({ts:Date.UTC(2022,0,1)+i*DAY,close:100000*Math.exp(.02*Math.sin(i/7)+.0001*i),low:100000*Math.exp(.02*Math.sin(i/7)+.0001*i),high:100000*Math.exp(.02*Math.sin(i/7)+.0001*i)}));ctx.state.intraday=[];for(const d of ctx.state.daily)for(let h=0;h<24;h+=4)ctx.state.intraday.push({ts:d.ts+h*HOUR,close:d.close,high:d.close,low:d.close});ctx.state.intradayHours=4;ctx.state.latest=ctx.state.daily.at(-1);ctx.state.latestIntraday=ctx.state.intraday.at(-1);ctx.computeFeatures();}
seed();
test('session statistics stay visible and historical cases use a doubled viewport',()=>{assert(html.includes('aria-labelledby="sessionStatsTitle"'));assert(!html.includes('<summary>Session statistics and applied research range</summary>'));assert(html.includes('#historicalCases>.table-wrap{max-height:840px}'));assert(script.includes("reverse().slice(0,440)"));});
test('numeric defaults satisfy declared bounds and steps',()=>{for(const m of html.matchAll(/<input\b([^>]+)>/g)){const a=Object.fromEntries([...m[1].matchAll(/([\w-]+)="([^"]*)"/g)].map(x=>[x[1],x[2]]));if(a.type!=='number'||!a.value)continue;const v=Number(a.value);assert(Number.isFinite(v),a.id);if(a.min!==undefined)assert(v>=Number(a.min),a.id);if(a.max!==undefined)assert(v<=Number(a.max),a.id);if(a.step!=='any'){const n=(v-Number(a.min??a.value??0))/Number(a.step??1);near(n,Math.round(n));}}});
test('completed 4H bar cannot supply an unfinished close',()=>{const a=[{ts:0,close:1},{ts:4*HOUR,close:2}];assert.equal(ctx.completedBar(a,2*HOUR,4*HOUR),null);assert.equal(ctx.completedBar(a,6*HOUR,4*HOUR).close,1);assert.equal(ctx.completedBar(a,8*HOUR,4*HOUR).close,2);});
test('daily feature uses prior completed bucket',()=>{const d=ctx.state.daily,mark=d[300].ts+16*HOUR;assert.equal(ctx.featureBefore(mark).index,299);assert.equal(ctx.featureBefore(d[300].ts+DAY).index,300);});
test('path coverage rejects missing buckets and unaligned windows',()=>{const a=[{ts:0,close:1},{ts:4*HOUR,close:2}];assert(ctx.completeSessionPath(a,0,8*HOUR,4*HOUR,1));assert.equal(ctx.completeSessionPath(a.slice(0,1),0,8*HOUR,4*HOUR,1),null);assert.equal(ctx.completeSessionPath(a,0,7*HOUR,4*HOUR,1),null);});
test('normalizer rejects nonpositive prices and conflicting duplicates',()=>{const a=ctx.normalize([{date:'2024-01-01',close:1},{date:'2024-01-01',close:2},{date:'2024-01-02',close:-1},{date:'2024-01-03',close:3}]);assert.equal(a.length,1);assert.equal(a[0].close,3);assert.equal(a.audit.conflicts,1);});
test('intraday constructors exclude unaligned entry and gaps',()=>{const s={...ctx.settings(),regime:'all'};assert(ctx.makeIntradayBase(s).length>100);assert.equal(ctx.makeIntradayBase({...s,entryHour:1}).length,0);const before=ctx.makeIntradayBase(s);const idx=ctx.state.intraday.findIndex(x=>x.ts===before[0].entryTs);const removed=ctx.state.intraday.splice(idx,1)[0];assert.equal(ctx.makeIntradayBase(s).length,before.length-1);ctx.state.intraday.splice(idx,0,removed);});
test('multi-day records use actual close availability and full tenor',()=>{const x=ctx.makeMultiDayBase({...ctx.settings(),mode:'multi',expiry:7})[0];assert.equal(x.entryTs,x.entryBucketTs+DAY);assert.equal(x.expiryTs-x.entryTs,7*DAY);assert.equal(x.entry,ctx.state.daily.find(d=>d.ts===x.entryBucketTs).close);});
test('RV excludes future candles and requires 30 complete returns',()=>{const d=ctx.state.daily,mark=d[100].ts,v=ctx.preEntryDeltaVol(mark);const old=d[100].close;d[100].close=1e9;near(v,ctx.preEntryDeltaVol(mark));d[100].close=old;assert(Number.isNaN(ctx.preEntryDeltaVol(d[29].ts)));const oldts=d[90].ts;d[90].ts+=HOUR;assert(Number.isNaN(ctx.preEntryDeltaVol(mark)));d[90].ts=oldts;});
test('minimum-width interval covers target even for one-sided samples',()=>{for(const r of [[1,2,3,4,5],[-5,-4,-3,-2,-1],[-8,-1,0,1,9]]){const x=ctx.minWidthRange(r,.8);assert(r.filter(v=>v>=x.lo&&v<=x.hi).length>=4);assert(x.lo<=0&&x.hi>=0);}});
test('delta inversion and put-call parity',()=>{for(const type of ['put','call'])for(const target of [.01,.25,.49]){const K=ctx.entryDeltaStrike(100000,8/8760,.03,.55,target,type),d=ctx.bsGreeks(100000,K,8/8760,.03,.55,type);near(d.delta,type==='put'?-target:target);}near(ctx.bsGreeks(100,100,.1,0,.5,'call').delta-ctx.bsGreeks(100,100,.1,0,.5,'put').delta,1);assert.equal(ctx.bsGreeks(100,0,.1,0,.5,'put').gamma,0);});
test('scenario accounting matches independent payoff formulas',()=>{ctx.state.range={lo:-2,hi:2};for(const mode of ['covered','csp','defined'])for(const terminal of [0,50,99,101,150,1000]){const s={strategy:'strangle',capitalMode:mode,credit:1,wing:5},u=ctx.scenarioTerms(100,terminal,s);let opt=1-Math.max(98-terminal,0);if(mode!=='csp')opt-=Math.max(terminal-102,0);if(mode==='defined')opt+=Math.max(93-terminal,0)+Math.max(terminal-107,0);near(u.optionPnl,opt);near(u.structurePnl,opt+(mode==='covered'?terminal-100:0));assert(u.capital>0);}});
test('scenario performance compounds only sequential valid returns',()=>{ctx.state.range={lo:-2,hi:2};const s={strategy:'strangle',capitalMode:'csp',credit:1,wing:5},a=[0,7,14].map(d=>({entryTs:d*DAY,expiryTs:d*DAY+HOUR,entry:100,expiry:100})),p=ctx.scenarioPerformance(a,s),r=1/98;near(p.meanReturn,r);near(p.equity,Math.pow(1+r,3));assert(Number.isFinite(p.cagr));assert.equal(p.overlaps,0);assert.equal(p.profitFactor,Infinity);const overlap=ctx.scenarioPerformance([{...a[0],expiryTs:8*DAY},a[1]],s);assert.equal(overlap.overlaps,1);assert.equal(overlap.compoundable,false);assert(Number.isNaN(overlap.cagr));});
test('expired model horizon is zero, not reset to full tenor',()=>{const original=ctx.Date;class Frozen extends Date{static now(){return Date.UTC(2024,0,5,9);}}ctx.Date=Frozen;assert.equal(ctx.modelHorizonYears({mode:'friday0dte',entryHour:0,expiryHour:8,sessionHours:8}),0);ctx.Date=original;});
function quoteFixture(){const base=[],rows=[];for(let i=0;i<120;i++){const entryTs=Date.UTC(2021,0,1+i*7),expiryTs=entryTs+8*HOUR;base.push({entryTs,expiryTs});for(const target of [.2,.3])rows.push({entryTime:new Date(entryTs).toISOString(),expiryTime:new Date(expiryTs).toISOString(),entrySpot:100,expirySpot:i%10===0?95:100,putStrike:target===.2?90:98,callStrike:target===.2?110:102,putPremium:target===.2?.2:2,callPremium:target===.2?.2:2,putCosts:.01,callCosts:.01,putTarget:target,callTarget:target});}return{base,raw:{convention:'usd-linear-per-btc',source:'synthetic regression fixture',rows}};}
test('quote contribution sum, capital and costs',()=>{const x=quoteFixture().raw.rows[0],o=ctx.quoteOutcome(x,false),m=ctx.quoteMetrics([x],false);near(m.ret,m.optionReturn+m.backingReturn);near(o.optionReturn,(.4-.02)/190);assert.throws(()=>ctx.validateObjectiveQuotes({convention:'btc-inverse',source:'x',rows:[x]}));});
test('final holdout cannot change selected quote candidate',()=>{const {base,raw}=quoteFixture(),q=ctx.quoteComparison(ctx.validateObjectiveQuotes(raw),base,.3,false);assert(q.profit);assert(q.validationN>=10);const changed=JSON.parse(JSON.stringify(raw));for(const r of changed.rows)if(Date.parse(r.entryTime)>=base[84].entryTs){r.putPremium=r.putTarget===.2?50:0;r.callPremium=0;}const q2=ctx.quoteComparison(ctx.validateObjectiveQuotes(changed),base,.3,false);assert.equal(q.profit.policy,q2.profit.policy);assert.notEqual(q.profit.test.ret,q2.profit.test.ret);});
test('quote data duplicate and units checks',()=>{const {raw}=quoteFixture();assert.throws(()=>ctx.validateObjectiveQuotes({...raw,rows:[raw.rows[0],raw.rows[0]]}));assert.throws(()=>ctx.validateObjectiveQuotes({...raw,rows:[{...raw.rows[0],callPremium:101}]}));});
test('selection risks can reject every quoted candidate',()=>{const {base,raw}=quoteFixture();for(const r of raw.rows){r.putPremium=0;r.callPremium=0;r.putCosts=10;}const q=ctx.quoteComparison(ctx.validateObjectiveQuotes(raw),base,.3,false);assert.equal(q.profit,null);});
test('explorer fixed winner is independent of later outcomes',()=>{const a=Array.from({length:100},(_,i)=>({entryTs:i*10,expiryTs:i*10+5,ret:i%2?1:-2,pathMinRet:-3,pathMaxRet:2})),x=ctx.explorerStudy(a,.3,5,.5,false),y=ctx.explorerStudy(a.map((v,i)=>i>=70?{...v,ret:99}:v),.3,5,.5,false);assert.equal(x.rows[0].pick.p,y.rows[0].pick.p);assert.equal(x.rows[0].pick.c,y.rows[0].pick.c);assert.notEqual(x.rows[0].hold.rate,y.rows[0].hold.rate);});
test('all panels render in four research modes with complete synthetic data',()=>{for(const mode of ['friday0dte','weekend','intraday','multi']){nodes.researchMode.value=mode;ctx.syncControls();ctx.run();assert(ctx.state.records.length>0);assert(nodes.researchState.textContent.includes('CURRENT'));assert(!nodes.caseBody.innerHTML.includes('undefined'));}});
test('empty regime sample renders without missing-value crashes',()=>{nodes.researchMode.value='friday0dte';nodes.regime.value='dd20';ctx.syncControls();ctx.run();assert.equal(ctx.state.records.length,0);});
console.log(`${count} regression groups passed`);
module.exports={ctx,nodes,seed};
